apiVersion: v1
kind: LimitRange
metadata:
  name: limits
  namespace: testnamespace
spec:
  limits:
  - default:
      cpu: 500m
      memory: 1024Mi
    defaultRequest:
      cpu: 300m
      memory: 850Mi
    type: Container
